set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR arm64)
set(CMAKE_SYSROOT "C:/Program Files (x86)/Microsoft SDKs/Windows Kits/10")
set(triple arm64-windows-msvc)

set(CMAKE_C_COMPILER C:/dev/toolchains/llvm-project/build/bin/clang.exe)
set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER C:/dev/toolchains/llvm-project/build/bin/clang++.exe)
set(CMAKE_CXX_COMPILER_TARGET ${triple})
set(CMAKE_RC_COMPILER C:/dev/toolchains/llvm-project/build/bin/llvm-rc.exe)
set(CMAKE_LINKER_TYPE LLD)
set(CMAKE_AR C:/dev/toolchains/llvm-project/build/bin/llvm-ar.exe)
set(CMAKE_RANLIB C:/dev/toolchains/llvm-project/build/bin/llvm-ranlib.exe)
set(CMAKE_MT C:/dev/toolchains/llvm-project/build/bin/llvm-mt)
set(CMAKE_ASM_COMPILER C:/dev/toolchains/llvm-project/build/bin/clang.exe)

set(CMAKE_SYSROOT "C:/dev/sysroots/WinSDK/10")
set(VULKAN_SDK "C:/VulkanSDK/1.4.313.1")
set(Qt6_DIR "C:/Qt/6.9.1/msvc2022_64/lib/cmake/Qt6")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
