set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(triple x86_64-unknown-linux-gnu)

set(CMAKE_C_COMPILER C:/dev/toolchains/llvm-project/build/bin/clang.exe)
set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER C:/dev/toolchains/llvm-project/build/bin/clang++.exe)
set(CMAKE_CXX_COMPILER_TARGET ${triple})
set(CMAKE_RC_COMPILER C:/dev/toolchains/llvm-project/build/bin/llvm-rc.exe)
set(CMAKE_LINKER_TYPE LLD)
set(CMAKE_AR C:/dev/toolchains/llvm-project/build/bin/llvm-ar.exe)
set(CMAKE_RANLIB C:/dev/toolchains/llvm-project/build/bin/llvm-ranlib.exe)
set(CMAKE_MT C:/dev/toolchains/llvm-project/build/bin/llvm-mt)
set(CMAKE_ASM_COMPILER C:/dev/toolchains/llvm-project/build/bin/clang.exe)

set(CMAKE_SYSROOT "C:/dev/sysroots/deb")
set(VULKAN_SDK "C:/dev/sysroots/vulkansdk-linux-x86_64-1.4.313.0/1.4.313.0")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(Rust_CARGO_TARGET ${triple})
set(ENV{RUSTFLAGS} "-C link-arg=-fuse-ld=lld")
