set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR X86_64)
set(triple x86_64-pc-windows-msvc)

set(CMAKE_C_COMPILER C:/dev/toolchains/llvm-project/build/bin/clang.exe)
set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER C:/dev/toolchains/llvm-project/build/bin/clang++.exe)
set(CMAKE_CXX_COMPILER_TARGET ${triple})
set(CMAKE_RC_COMPILER C:/dev/toolchains/llvm-project/build/bin/llvm-rc.exe)
set(CMAKE_LINKER_TYPE LLD)
set(CMAKE_AR C:/dev/toolchains/llvm-project/build/bin/llvm-ar.exe)
set(CMAKE_RANLIB C:/dev/toolchains/llvm-project/build/bin/llvm-ranlib.exe)
set(CMAKE_MT C:/dev/toolchains/llvm-project/build/bin/llvm-mt)
set(CMAKE_ASM_COMPILER C:/dev/toolchains/llvm-project/build/bin/clang.exe)

set(CMAKE_SYSROOT "C:/dev/sysroots/WinSDK/10")
set(VULKAN_SDK "C:/VulkanSDK/1.4.313.1")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)

set(Rust_CARGO_TARGET ${triple})
