

import { MyButton } from "MyButton.slint";
import { Styles } from "styles.slint";
export component MyApp {
    width: 300px;
    height: 300px;
    Rectangle {
        border-width: 5px;
        border-color: Styles.fun-gradient;
        border-radius: 30px;
    }

    property <int> counter: 0;
    HorizontalLayout {
        for i in 5: Image {
            source: @image-url("Ghostscript_Tiger.svg");
            width: root.width / 5;
            colorize: white;
        }
    }
    HorizontalLayout {
        for i in 5: Image {
            source: @image-url("Ghostscript_Tiger.svg");
            width: root.width / 5;
            opacity: counter > i ? 1 : 0;
            animate opacity {
                duration: 500ms;
            }
        }
    }

    Text {
        text: "Rate my demo";
        y: Styles.margin;
        font-size: 30px;
    }

    MyButton {
        y: root.height - self.height - Styles.margin;
        label: "+";
        clicked => {
            if (counter < 5) {
                counter += 1;
            } else {
                counter = 0;
            }
        }
    }
}
