import { Styles } from "styles.slint";
export component MyButton {
    width: myText.width + Styles.margin * 2;
    height: myText.height + Styles.margin * 2;
    in property <string> label;
    callback clicked();
    Rectangle {
        background: Styles.fun-gradient;
        width: 150px;
        height: 60px;
        border-radius: 5px;

        myText := Text {
            text: label;
            font-size: 24px;
            color: black;
        }

        TouchArea {
            clicked => {
                root.clicked();
            }
        }
    }
}
